-- Create the leaderboard table
CREATE TABLE public.leaderboard (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    score INTEGER DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.leaderboard ENABLE ROW LEVEL SECURITY;

-- Policy: Allow everyone to read the leaderboard
CREATE POLICY "Enable read access for all users" ON public.leaderboard
    FOR SELECT USING (true);

-- Policy: Allow authenticated users to insert scores (or everyone if you prefer, but auth is better)
-- Since our backend uses the Service Role Key (or tries to), it bypasses RLS.
-- However, if falling back to the Anon key, we need a policy.
-- For this MVP, let's allow public inserts to ensure it works easily, 
-- or strictly authenticated if the user is logged in.
CREATE POLICY "Enable insert for authenticated users only" ON public.leaderboard
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- OPTIONAL: If you want valid public uploads (since we fire from client sometimes? No, we fire from backend mostly? 
-- Wait, the client code fetches to /api/score, so the SERVER inserts it. 
-- The Server uses the Service Role Key (bypasses RLS) OR the Anon Key (subject to RLS).
-- If server uses Anon Key, we need to allow inserts.
-- Let's add a policy for anon inserts just in case the Service Role Key is missing.
CREATE POLICY "Enable insert for all users (fallback)" ON public.leaderboard
    FOR INSERT WITH CHECK (true);
